import type { Product } from './types';

export const SAMPLE_PRODUCTS: Product[] = [
	{
		id: '1',
		name: 'Zip Collar Sweater Jacket',
		color: 'True Black',
		price: 255000,
		special: 127500,
		category: 'Campera',
		image: '/assets/product-1.jpg',
		hover: '/assets/product-1-hover.jpg',
		images: [
			'/assets/product-1.jpg',
			'/assets/product-2.jpg',
			'/assets/product-3.jpg',
			'/assets/product-4.jpg'
		],
		sizes: ['S', 'M', 'XXL'],
		sku: '0RNHS5080100M',
		description:
			'Campera tejida realizada en hilado de algodón, viscosa con cierre metálico y tira cierre marcario. Cuello tejido tipo camisero, y bolsillos laterales. Logo bordado simple a 1 color en pecho al tono del tejido.',
		composition: 'Algodón y viscosa. Cuidados según etiqueta interior.',
		order: 0
	},
	{
		id: '2',
		name: 'Ss Rubber Logo Tee',
		color: 'CLASSIC BLUE',
		price: 69500,
		special: 27800,
		category: 'Remera',
		image: '/assets/product-1.jpg',
		hover: '/assets/product-1-hover.jpg',
		images: ['/assets/product-1.jpg', '/assets/product-1-hover.jpg'],
		sizes: ['S', 'M', 'L', 'XL'],
		sku: '0RNPR102001',
		description: 'Remera manga corta de algodón suave con estampa frontal en relieve.',
		composition: '100% Algodón peinado.',
		order: 1
	},
	{
		id: '3',
		name: 'Regular Denim',
		color: 'True Black',
		price: 185000,
		special: 74000,
		category: 'Denim',
		image: '/assets/product-2.jpg',
		hover: '/assets/product-2-hover.jpg',
		images: ['/assets/product-2.jpg', '/assets/product-2-hover.jpg'],
		sizes: ['30', '32', '34', '36'],
		sku: '0RNDN204002',
		description: 'Pantalón de jean corte regular con tiro medio y terminación clásica.',
		composition: '98% Algodón, 2% Elastano.',
		order: 2
	},
	{
		id: '4',
		name: 'Relaxed Denim Light Grey',
		color: 'LIGHT GREY',
		price: 185000,
		special: 74000,
		category: 'Denim',
		image: '/assets/product-3.jpg',
		hover: '/assets/product-3-hover.jpg',
		images: ['/assets/product-3.jpg', '/assets/product-3-hover.jpg'],
		sizes: ['30', '32', '34'],
		sku: '0RNDN204003',
		description: 'Denim fit relajado con proceso de lavado suave en tono gris.',
		composition: '100% Algodón.',
		order: 3
	},
	{
		id: '5',
		name: 'Ss Basic Over Tee W/Pkt',
		color: 'BALLAD BLUE',
		price: 75000,
		special: 30000,
		category: 'Remera',
		image: '/assets/product-4.jpg',
		hover: '/assets/product-4-hover.jpg',
		images: ['/assets/product-4.jpg', '/assets/product-4-hover.jpg'],
		sizes: ['S', 'M', 'L'],
		sku: '0RNPR102004',
		description: 'Remera cuello redondo de calce holgado con bolsillo aplicado en el pecho.',
		composition: '100% Algodón.',
		order: 4
	},
	{
		id: '6',
		name: 'Ls Solid Oxford Shirt',
		color: 'Bordo',
		price: 155000,
		special: 62000,
		category: 'Camisa',
		image: '/assets/product-5.jpg',
		hover: '/assets/product-5-hover.jpg',
		images: ['/assets/product-5.jpg', '/assets/product-5-hover.jpg'],
		sizes: ['M', 'L', 'XL'],
		sku: '0RNCM301005',
		description: 'Camisa manga larga tejida en hilado Oxford con cuello abotonado y logo bordado.',
		composition: '100% Algodón Oxford.',
		order: 5
	},
	{
		id: '7',
		name: 'Ss Basic Over Tee W/Pkt',
		color: 'PARFAITH PINK',
		price: 75000,
		special: 30000,
		category: 'Remera',
		image: '/assets/product-6.jpg',
		hover: '/assets/product-6-hover.jpg',
		images: ['/assets/product-6.jpg', '/assets/product-6-hover.jpg'],
		sizes: ['S', 'M', 'L', 'XL'],
		sku: '0RNPR102006',
		description: 'Remera oversize con bolsillo en tono pastel, suave al tacto.',
		composition: '100% Algodón.',
		order: 6
	},
	{
		id: '8',
		name: 'Ss Basic Over Tee',
		color: 'Bright White',
		price: 75000,
		special: 30000,
		category: 'Remera',
		image: '/assets/product-7.jpg',
		hover: '/assets/product-7-hover.jpg',
		images: ['/assets/product-7.jpg', '/assets/product-7-hover.jpg'],
		sizes: ['S', 'M', 'L'],
		sku: '0RNPR102007',
		description: 'Básico infaltable de corte moderno y cuello tejido en ribb.',
		composition: '100% Algodón.',
		order: 7
	},
	{
		id: '9',
		name: 'L/S Wide Stripe Shirt',
		color: 'Dark Sapphire',
		price: 165000,
		special: 66000,
		category: 'Camisa',
		image: '/assets/product-8.jpg',
		hover: '/assets/product-8-hover.jpg',
		images: ['/assets/product-8.jpg', '/assets/product-8-hover.jpg'],
		sizes: ['M', 'L', 'XL'],
		sku: '0RNCM301008',
		description: 'Camisa a rayas anchas con silueta regular y botones contrastantes.',
		composition: '100% Algodón.',
		order: 8
	},
	{
		id: '10',
		name: 'Ls Color Block Tape Track Jkt',
		color: 'Olive',
		price: 235500,
		special: 94200,
		category: 'Campera',
		image: '/assets/product-9.jpg',
		hover: '/assets/product-9-hover.jpg',
		images: ['/assets/product-9.jpg', '/assets/product-9-hover.jpg'],
		sizes: ['S', 'M', 'L', 'XL'],
		sku: '0RNJK402009',
		description: 'Campera deportiva con cinta lateral en mangas y bloques de color.',
		composition: 'Poliéster y algodón.',
		order: 9
	},
	{
		id: '11',
		name: 'Ls Floral Print Shirt',
		color: 'Sargasso Sea',
		price: 175000,
		special: 70000,
		category: 'Camisa',
		image: '/assets/product-10.jpg',
		hover: '/assets/product-10-hover.jpg',
		images: ['/assets/product-10.jpg', '/assets/product-10-hover.jpg'],
		sizes: ['M', 'L'],
		sku: '0RNCM301010',
		description: 'Camisa estampada floral de diseño exclusivo sobre fondo oscuro.',
		composition: '100% Viscosa.',
		order: 10
	},
	{
		id: '12',
		name: 'Slim Taper Twill Pale Khaki',
		color: 'Pale Khaki',
		price: 165000,
		special: 66000,
		category: 'Pantalón',
		image: '/assets/product-11.jpg',
		hover: '/assets/product-11-hover.jpg',
		images: ['/assets/product-11.jpg', '/assets/product-11-hover.jpg'],
		sizes: ['30', '32', '34', '36'],
		sku: '0RNPN501011',
		description: 'Pantalón chino en gabardina de algodón esmerilada con pierna cónica.',
		composition: '97% Algodón, 3% Elastano.',
		order: 11
	}
];
